//LOGIN
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';

// INTERVIEW
export const POST_INTERVIEW_REQUEST = 'POST_INTERVIEW_REQUEST';
export const POST_INTERVIEW_SUCCESS = 'POST_INTERVIEW_SUCCESS';
export const POST_INTERVIEW_FAILURE = 'POST_INTERVIEW_FAILURE';
export const NAME_CHANGED = 'NAME_CHANGED';
export const SURNAME_CHANGED = 'SURNAME_CHANGED';
export const PHONE_CHANGED = 'PHONE_CHANGED';
export const PRESENT_CHANGED = 'PRESENT_CHANGED';
export const REFERER_FIRSTNAME_CHANGED = 'REFERER_FIRSTNAME_CHANGED';
export const REFERER_LASTNAME_CHANGED = 'REFERER_LASTNAME_CHANGED';
export const REFERER_PHONE_CHANGED = 'REFERER_PHONE_CHANGED';
export const STAND_AREA_CHANGED = 'STAND_AREA_CHANGED';
export const STAND_TIME_CHANGED = 'STAND_TIME_CHANGED';
export const STAND_NAME_CHANGED = 'STAND_NAME_CHANGED';
export const SITE_NAME_CHANGED = 'SITE_NAME_CHANGED';
export const BLOCK_NAME_CHANGED = 'BLOCK_NAME_CHANGED';
export const FLAT_NO_CHANGED = 'FLAT_NO_CHANGED';
export const INTERVIEW_RESULT_CHANGED = 'INTERVIEW_RESULT_CHANGED';
export const INTERVIEW_RESULT_DETAIL_CHANGED = 'INTERVIEW_RESULT_DETAIL_CHANGED';
export const REVISIT_TIME_CHANGED = 'REVISIT_TIME_CHANGED';
export const OTHER_ISS_CHANGED = 'OTHER_ISS_CHANGED';
export const FILE_CHANGED = 'FILE_CHANGED';
export const PHOTO_CHANGED = 'PHOTO_CHANGED';
export const VOICE_CHANGED = 'VOICE_CHANGED';
export const LONG_CHANGED = 'LONG_CHANGED';
export const LAT_CHANGED = 'LAT_CHANGED';
export const OFFERED_PRODUCT_CHANGED = 'OFFERED_PRODUCT_CHANGED';
